[build]
  base = "frontend"
  command = "CI=false npm install && CI=false npm run build"
  publish = "build"
  environment = { NODE_VERSION = "18" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 