name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependencies
        working-directory: ./frontend
        run: npm install

      - name: Build
        working-directory: ./frontend
        run: npm run build

      - name: Install sshpass
        run: sudo apt-get install sshpass

      - name: Deploy to Server
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
          SERVER_IP: 80.78.242.68
          SERVER_USER: root
          SERVER_PASS: ${{ secrets.SERVER_PASS }}
        run: |
          cd frontend/build
          sshpass -p "$SERVER_PASS" ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP 'mkdir -p /var/www/html'
          sshpass -p "$SERVER_PASS" scp -o StrictHostKeyChecking=no -r ./* $SERVER_USER@$SERVER_IP:/var/www/html/ 